### ISSUE TITLE
Error when compiling related to libboost 1.74.0

### ISSUE THREAD

**Issue by Camilo-sismo** [SED-EEW/SED-EEW-SeisComP-contributions#20]
When we tried to compile on Debian 11 using  libboost 1.74.0 we had next errors:

sceewenv/main.cpp:144:85: error: '_4' was not declared in this scope
  144 |    _eewProc.setEnvelopeCallback(boost::bind(&App::handleEnvelope, this, _1, _2, _3, _4));
sceewenv/main.cpp:144:81: error: '_3' was not declared in this scope
  144 |    _eewProc.setEnvelopeCallback(boost::bind(&App::handleEnvelope, this, _1, _2, _3, _4));
....

We added 
		#include <boost/bind/placeholders.hpp>
		using namespace boost::placeholders;
To:
sed-addons/apps/eew/scfinder/main.cpp
sed-addons/test/eewamps/testprocs.cpp
sed-addons/test/eewamps/testgba.cpp
sed-addons/test/eewamps/testgba.cpp

After modifications it worked well.

We are using 5.1.1 tag

**Comment by FMassin** [comment]
Thanks @Camilo-sismo 

@gempa-jabe : I believe you already fixed this kind of thing in sceewenv with #18 but should I do something similar for scfinder ?

**Comment by gempa-jabe** [comment]
Yes, you should consider it as it will break with later boost version if `boost::bind` is being used in scfinder. I don't know right now.
